language: ruby

cache: bundler

sudo: false

before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    # --dev improves JRuby startup time
    # --debug reports proper coverage to SimpleCov
    # See https://github.com/jruby/jruby/wiki/Improving-startup-time
    - JRUBY_OPTS="--dev --debug"

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby-9.2.5.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0
  fast_finish: true
